# Windows-like auto-scrolling. Press `button_id` to start scrolling,
# then move your mouse up or down. The longer the distance between the
# cursor and the starting point, the faster you scroll. Remove/comment
# out whole section if you don't want it.
[scroll]
# Device with buttons. Use `xinput list` and `xinput test-xi2 --root` to
# determine.
device = "Wacom Bamboo Pen stylus"
# Change it if you have many devices with the same name.
subdevice = 0
# `hold = false` means click once to enable, click once to disable.
# Recommended `false` on tablets, as it's annoying when you connectivity
# while using `hold = true`.
hold = false
# Scrolling speed. Has different effect on different screen resolutions.
# Recommended to set `speed` to high value and decrease system-wide
# scrolling speed as much as possible. Equation: `speed`ร`distance`[px]
# รท1_000_000_000 = emulated mouse wheel rolls.
speed = 600000
# Which button toggles scrolling. Button 2 is the middle mouse button.
# Button 3 is upper button on Wacom Bamboo Pen.
button_id = 3

# Click using keyboard. Active only until `timeout_ms` has passed since
# the last time any of grabbed devices was used. Remove/comment out
# whole section if you don't want it.
[keyboard_click]
# Device that moves or has buttons, used to determine timeout. Use
# `xinput list` and `xinput test-xi2 --root` to determine.
device = "Wacom Bamboo Pen stylus"
# Change it if you have many devices with the same name.
subdevice = 0
# How much time must pass until keys go back to normal.
timeout_ms = 500
# Key that emulates left mouse button.
# **DO NOT USE TOGGLE BUTTON (CapsLock etc.)**
key_lmb = 25 # W
# Key that emulates right mouse button.
# **DO NOT USE TOGGLE BUTTON (CapsLock etc.)**
key_rmb = 26 # E
# Key that will be used for temporary purposes.
# **DO NOT USE TOGGLE BUTTON (CapsLock etc.)**
key_unused1 = 106 # numpad /
# Key that will be used for temporary purposes.
# **DO NOT USE TOGGLE BUTTON (CapsLock etc.)**
key_unused2 = 63 # numpad *
